CREATE TABLE CART (
	pk_id INT PRIMARY KEY
);

CREATE TABLE CONSOLE (
	pk_name VARCHAR(20) PRIMARY KEY
);

CREATE TABLE GAME (
	pk_title VARCHAR(40) PRIMARY KEY,
	fk_console VARCHAR(40) NOT NULL,
	price INT NOT NULL,
	FOREIGN KEY fk_console REFERENCES CONSOLE(pk_name)
);

CREATE TABLE TYPE (
	pk_type VARCHAR(20) PRIMARY KEY
);

CREATE TABLE CLIENT (
	pk_email VARCHAR(40) PRIMARY KEY,
	lastName VARCHAR(20) NOT NULL,
	firstName VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	birthDate DATE NOT NULL,
	fk_cart INT NOT NULL,
	FOREIGN KEY (fk_cart) REFERENCES CART(pk_id)
);

CREATE TABLE GAME_TYPE (
	fk_game VARCHAR(40),
	fk_type VARCHAR(20),
	FOREIGN KEY (fk_type) REFERENCES TYPE(pk_type),
	FOREIGN KEY (fk_game) REFERENCES GAME(pk_title),
	PRIMARY KEY (fk_game, fk_type)
);

CREATE TABLE LIGNE_CART (
	fk_cart INT,
	fk_game VARCHAR(40),
	quantity INT NOT NULL,
	PRIMARY KEY (fk_cart, fk_game),
	FOREIGN KEY (fk_cart) REFERENCES CART(pk_id),
	FOREIGN KEY (fk_game) REFERENCES GAME(pk_title)
);

CREATE TABLE CONSOLE_GAME (
	fk_console VARCHAR(20),
	fk_game VARCHAR(40),
	FOREIGN KEY (fk_console) REFERENCES CONSOLE(pk_name),
	FOREIGN KEY (fk_game) REFERENCES GAME(pk_title),
	PRIMARY KEY (fk_console, fk_game)
);
